version: '3.5'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD:

  bot:
    image: fin_bot
    environment:
      CREATE_USER_INFO_TABLE: "yes"
      CREATE_USER_HISTORY_TABLE: "yes"
      TOKEN: 5808047150:AAGygYNLbC-GBhxgu80CItF7BYMbYhGmBCg
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD:
      DBNAME: postgres
      SSLMODE: disable